### ISSUE TITLE
"From Name" and "From  Email Adress" and "Rich Text" not working

### ISSUE THREAD

**Issue by JamesBart** [TobinShields/Zaqar_EmailSpoofer#3]
Hello guys,
I have several problems :(

First of all:

The **delivery of the email works** but the as mentioned in the headline the From name and From address doesn't change. I send the emails over a Webserver on AWARDSPACE.COM with a mail account I created in there. And anytime I send an email the address and name of my mail account is shown not the ones I entered. Do you have any idea what could be the problem here?

Second of all the rich text editor doesn't work somehow. I paste an html code in this code "box" but when I send the email the body simply is the html code in plain text!
Please help!!!

**Comment by TobinShields** [comment]
Hey @JamesBart sorry for the long delay on the reply. This has gotten an upgrade since then... would you mind trying again? 

Also, when using the rich text editor, there is a button in the toolbar to allow for you insert HTML. If you just paste it in without using that tool it will treat the HTML and just raw text.
